---
npm:
  platforms:
    - name: linux
      os: alpine
      architecture: x86_64
      node_versions:
        - "12"

docker:
  builds:
    - path: .
      dockerfile: Dockerfile
      docker_repo: resin/docs
